auth_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.auth_login, name='auth_app.auth_login'),
    path('logout/', views.auth_logout, name='auth_app.auth_logout'),
    path('register/', views.auth_register, name='auth_app.auth_register'),
    path('profile/', views.auth_profile, name='auth_app.auth_profile'),
    path('passwordChange/', views.auth_passwordChange, name='auth_app.auth_passwordChange'),
]

movieStreamingApp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('auth/', include('auth_app.urls')),
    path('movie/', include('movie_app.urls')),
    path('series/', include('series_app.urls')),
    path('search/', include('search_app.urls')),
    path('comments/', include('comment_app.urls')),
    path('bookmarks/', include('bookmark_app.urls')),

    path('watchHistory/<str:content_type>', views.watchHistory, name='watchHistory'),

    path('searchTerms/', views.getSearchTerms),

    path('cast/create', views.cast_create, name='cast_create'),
    path('cast/<int:id>', views.cast, name='cast'),
]

series_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('<int:id>/<int:current_season>/<int:current_episode>/<str:resolution>', views.series, name='series_app.series'),
    path('<int:id>/<int:current_season>/<int:current_episode>', views.series, name='series_app.series'),
    path('<int:id>/<int:current_season>', views.series, name='series_app.series'),
    path('<int:id>', views.series, name='series_app.series'),
    path('create/', views.series_create, name='series_app.series_create'),
    path('upload/', views.series_upload, name='series_app.series_upload'),
    path('upload/<int:id>', views.series_upload, name='series_app.series_upload'),
    path('download/<str:source>', views.series_download, name='series_app.series_download'),
    path('stream/<str:source>/', views.series_stream, name='series_app.series_stream'),
]

series_app/models.py
from django.db import models
from movieStreamingApp.models import Genre, Country, Production, Director, Cast

class Series(models.Model):
    title       = models.CharField(max_length=255)
    poster      = models.CharField(max_length=255, unique=True)
    releaseDate = models.DateField()
    description = models.TextField()
    status      = models.CharField(max_length=10, choices=[('Ongoing','Ongoing'),('Completed','Completed'),('Hiatus','Hiatus'),('Canceled','Canceled')])
    rating      = models.CharField(max_length=5, choices=[('G','G'),('PG','PG'),('PG-13','PG-13'),('R','R'),('NC-17','NC-17')])
    addedDateTime = models.DateTimeField(auto_now_add=True)
    genres      = models.ManyToManyField(Genre, blank=True)
    countries   = models.ManyToManyField(Country, blank=True)
    productions = models.ManyToManyField(Production, blank=True, null=True)
    directors   = models.ManyToManyField(Director, blank=True, null=True)
    casts       = models.ManyToManyField(Cast, blank=True, null=True)
    views       = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    

class Season(models.Model):
    series = models.ForeignKey(Series, blank=True, on_delete=models.CASCADE)
    season = models.PositiveIntegerField()

    def __str__(self):
        return self.series.title + '-' + str(self.season)
    

class Episode(models.Model):
    season = models.ForeignKey(Season, blank=True, on_delete=models.CASCADE)
    episode = models.PositiveBigIntegerField()

    def __str__(self):
        return self.season.series.title + '-' + str(self.season.season) + '-' + str(self.episode)


class SeriesResource(models.Model):
    episode    = models.ForeignKey(Episode, on_delete=models.CASCADE)
    resolution = models.CharField(max_length=5, choices=[('320p','320p'),('480p','480p'),('720p','720p'),('1080p','1080p')])
    source     = models.CharField(max_length=255, unique=True)

    class Meta:
        unique_together = ('episode', 'resolution')

    def __str__(self):
        return self.source

series_app/forms.py
from django import forms
from datetime import datetime
from .models import Series, SeriesResource
from movieStreamingApp.models import Genre, Country


class SeriesForm(forms.ModelForm):
    year_list = range(datetime.now().year, datetime.now().year-200, -1)

    class Meta:
        model = Series
        fields = ['title','poster','releaseDate','status','rating','description','genres','countries','productions','directors','casts']

    releaseDate = forms.DateField(
        label='Release Date',
        widget=forms.SelectDateWidget(
            years=year_list
        )
    )

    poster = forms.FileField(
        label='Poster',
        widget=forms.FileInput({
            'accept':'image/jpeg,image/jpg,image/jfif'
        })
    )

    genre = forms.ModelMultipleChoiceField(
        label='Genres',
        queryset = Genre.objects.filter().order_by('name'),
        widget=forms.CheckboxSelectMultiple()
    )

    country = forms.ModelMultipleChoiceField(
        label='Countries',
        queryset = Country.objects.filter().order_by('name'),
        widget=forms.CheckboxSelectMultiple()
    )

    director = forms.CharField(
        label='Directors*',
        required=False,
        widget=forms.TextInput({'list':'director-list'})
    )

    codirector = forms.CharField(
        label='Co-Director - optional',
        required=False,
        widget=forms.TextInput({'list':'director-list'})
    )

    cast = forms.CharField(
        label='Casts*',
        required=False,
        widget=forms.TextInput({'list':'cast-list'})
    )

    cocast1 = forms.CharField(
        label='Co-Cast - optional',
        required=False,
        widget=forms.TextInput({'list':'cast-list'})
    )

    cocast2 = forms.CharField(
        label='Co-Cast - optional',
        required=False,
        widget=forms.TextInput({'list':'cast-list'})
    )

    production = forms.CharField(
        label='Production Companies*',
        required=False,
        widget=forms.TextInput({'list':'production-list'})
    )

    coproduction1 = forms.CharField(
        label='Co-Production Company - optional',
        required=False,
        widget=forms.TextInput({'list':'production-list'})
    )

    coproduction2 = forms.CharField(
        label='Co-Production Company - optional',
        required=False,
        widget=forms.TextInput({'list':'production-list'})
    )

    def clean_title(self):
        value = self.cleaned_data.get('title')
        return value.strip()

    def clean_poster(self):
        value = self.cleaned_data.get('poster')
        if value.content_type not in ['image/jpeg', 'image/jpg', 'image/jfif']:
            raise forms.ValidationError('Poster must be either JPEG or JPG')
        return value

    def clean_director(self):
        director = self.cleaned_data.get('director')
        return director.strip()

    def clean_codirector(self):
        codirector = self.cleaned_data.get('codirector')
        return codirector.strip()
    
    def clean_cast(self):
        cast = self.cleaned_data.get('cast')
        return cast.strip()
    
    def clean_cocast1(self):
        cocast1 = self.cleaned_data.get('cocast1')
        return cocast1.strip()
    
    def clean_cocast2(self):
        cocast2 = self.cleaned_data.get('cocast2')
        return cocast2.strip()

    def clean_production(self):
        production = self.cleaned_data.get('production')
        return production.strip()
    
    def clean_coproduction1(self):
        coproduction1 = self.cleaned_data.get('coproduction1')
        return coproduction1.strip()
    
    def clean_coproduction2(self):
        coproduction2 = self.cleaned_data.get('coproduction2')
        return coproduction2.strip()
    

class SeriesResourceForm(forms.Form):   # having problems with ModelForm, episode cannot be overidden
    series = forms.IntegerField(
        label="Series",
        widget=forms.NumberInput()
    )

    season = forms.IntegerField(
        label="Season",
        widget=forms.NumberInput()
    )

    episode = forms.IntegerField(
        label="Episode",
        widget=forms.NumberInput()
    )

    resolution = forms.ChoiceField(
        label="Resolution",
        choices=[('320p','320p'),('480p','480p'),('720p','720p'),('1080p','1080p')]
    )

    source = forms.FileField(
        label='Video File',
        widget=forms.FileInput({
            'accept':'video/mp4'
        })
    )

    sourceFileName = forms.CharField(
        widget=forms.TextInput({
            'style':'display:none;',
            'readonly':'readonly'
        })
    )

    def clean_source(self):
        value = self.cleaned_data.get('source')
        if not value.content_type == 'video/mp4':
            raise forms.ValidationError('File must be MP4')
        return value
    
    def clean_season(self):
        value = self.cleaned_data.get('season')
        if value <= 0:
            raise forms.ValidationError('Invalid season number')
        return value
    
    def clean_episode(self):
        value = self.cleaned_data.get('episode')
        if value <= 0:
            raise forms.ValidationError('Invalid episode number')
        return value
        

series_app/templates/series.html
{% extends 'base_page.html' %}

{% load static %}

{% block title %} <title> MovWave | {{series.title}} </title> {% endblock %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'css/movie.css' %}">
    <link rel="stylesheet" href="{% static 'css/series.css' %}">
{% endblock %}

{% block content %} 
    <div class="blackoverlay"></div>
    <div class="video-wrapper">
        <video class="video-player" id="video-player" controls muted="muted">                
            <source src="{% url 'series_app.series_stream' source=series_resource.source %}" type="video/mp4" />
        </video>
    </div>
    <div class="button-wrapper">
        <div>
            <a class="download-button" href="{% url 'series_app.series_download' source=series_resource.source %}"> Download </a>
            {% if user.is_superuser %}
            <a class="upload-button" href="{% url 'series_app.series_upload' id=series.id %}"> Upload </a>
            {% endif %}
        </div>
        <div>
        {% for item in resolutions %}
            {% if item.resolution == series_resource.resolution%}
                <a class="current-resolution-button" href="{% url 'series_app.series' id=series.id current_season=current_season.season current_episode=current_episode.episode resolution=item.resolution %}"> {{item.resolution}} </a>
            {% else %}
                <a class="available-resolution-button" href="{% url 'series_app.series' id=series.id current_season=current_season.season current_episode=current_episode.episode resolution=item.resolution %}"> {{item.resolution}} </a>
            {% endif %}
        {% endfor %}
        </div>
    </div>
    <div class="season-wrapper">
        <div>
            <h2> Seasons </h2>
        </div>
        <div class="seasons">
            {% for ss in seasons %}
                {% if ss.season == current_season.season %}
                    <a class="season current-season" href="{% url 'series_app.series' id=series.id current_season=ss.season %}"> {{ss.season}} </a>
                {% else %}
                    <a class="season" href="{% url 'series_app.series' id=series.id current_season=ss.season %}"> {{ss.season}} </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="season-wrapper">
        <div>
            <h2> Episodes </h2>
        </div>
        <div class="seasons">
            {% for ep in episodes %}
                {% if ep.episode == current_episode.episode %}
                    <a class="season current-season" href="{% url 'series_app.series' id=series.id current_season=current_season.season current_episode=ep.episode %}"> {{ep.episode}} </a>
                {% else %}
                    <a class="season" href="{% url 'series_app.series' id=series.id id=series.id current_season=current_season.season current_episode=ep.episode %}"> {{ep.episode}} </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="metadata-wrapper">
        <div class="poster-wrapper">
            <img src="{{series.poster}}">
        </div>
        <div class="description-wrapper">
            <div class="header-wrapper">
                <h1> {{series.title}} ({{series.releaseDate.year}}) </h1>
                {% if user.is_authenticated %}
                    {% if bookmarked %}
                        <form method="POST" id="bookmarkForm" action="{% url 'bookmark_app.bookmark' content_type='series' id=series.id %}">
                            {% csrf_token %}
                            <button class="bookmark_button" type="submit"> 
                                <svg class="bookmarked" xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 -960 960 960" width="48px" fill="#ffffff"><path d="M200-120v-640q0-33 23.5-56.5T280-840h400q33 0 56.5 23.5T760-760v640L480-240 200-120Zm80-122 200-86 200 86v-518H280v518Zm0-518h400-400Z"/></svg> 
                            </button>
                        </form>
                    {% else %}
                        <form method="POST" id="bookmarkForm" action="{% url 'bookmark_app.bookmark' content_type='series' id=series.id %}">
                            {% csrf_token %}
                            <button class="bookmark_button" type="submit"> 
                                <svg class="not-bookmarked" xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 -960 960 960" width="48px" fill="#ffffff"><path d="M200-120v-640q0-33 23.5-56.5T280-840h400q33 0 56.5 23.5T760-760v640L480-240 200-120Zm80-122 200-86 200 86v-518H280v518Zm0-518h400-400Z"/></svg> 
                            </button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
            <div>
                <p> {{series.description}} </p>
            </div>
            <div class="grid-wrapper">
                <div> <p> Release Date : </p> </div>
                <div> <p> {{series.releaseDate}} </p> </div>
                <div> <p> Genre : </p> </div>
                <div> <p> 
                    {% for genre in genres %} 
                        <a href="{% url 'search_app.search' content_type='series' search_type='genre' search=genre.name %}"> {{genre.name}} </a>
                        {% if not forloop.last %} , {% endif %}
                    {% endfor %} 
                </p> </div>

                <div> <p> Status : </p> </div>
                <div> <p> <a href="{% url 'search_app.search' content_type='series' search_type='status' search=series.status %}"> {{series.status}} </a> </p> </div>
                
                <div> <p> Production : </p> </div>
                {% if productions %}
                    <div> <p> 
                        {% for production in productions %} 
                            <a href="{% url 'search_app.search' content_type='series' search_type='production' search=production.name %}"> {{production.name}} </a>
                            {% if not forloop.last %} , {% endif %}
                        {% endfor %} 
                    </p> </div>
                {% else %}
                    <div> <p> N/A </p> </div>
                {% endif %}
                
                <div> <p> Director : </p> </div>
                {% if directors %}
                    <div> <p> 
                        {% for director in directors %} 
                            <a href="{% url 'search_app.search' content_type='series' search_type='director' search=director.name %}"> {{director.name}} </a>
                            {% if not forloop.last %} , {% endif %}
                        {% endfor %} 
                    </p> </div>                
                {% else %}
                    <div> <p> N/A </p> </div>
                {% endif %}
                
                <div> <p> Cast : </p> </div>
                {% if casts %}
                    <div> <p> 
                        {% for cast in casts %} 
                            <a href="{% url 'search_app.search' content_type='series' search_type='cast' search=cast.name %}"> {{cast.name}} </a>
                            {% if not forloop.last %} , {% endif %}
                        {% endfor %} 
                    </p> </div>                
                {% else %}
                    <div> <p> N/A </p> </div>
                {% endif %}
                
                <div> <p> Country : </p> </div>
                <div> <p> 
                    {% for country in countries %} 
                        <a href="{% url 'search_app.search' content_type='series' search_type='country' search=country.name %}"> {{country.name}} </a>
                        {% if not forloop.last %} , {% endif %}
                    {% endfor %} 
                </p> </div>

                <div> <p> Rating : </p> </div>
                <div> <p> <a href="{% url 'search_app.search' content_type='series' search_type='rating' search=series.rating %}"> {{series.rating}} </a> </p> </div>
            </div>
        </div>
    </div>
    {% include 'cast_card.html' %}
    {% include 'comment.html' %}
{% endblock %} 
{% block script %}
    {% if user.is_authenticated %}
    <script src="{% static 'javascript/bookmarkForm_handler.js' %}" defer > </script>
    {% endif %}
{% endblock %}

series_app/templates/series_create.html
{% extends 'base_page.html' %}

{% load static %}

{% block title %} <title> MovWave | Create Series </title> {% endblock %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'css/movie_form.css' %}">
{% endblock %}

{% block content %} 
    <form id="form" class="form" method="POST" enctype="multipart/form-data" action="{% url 'series_app.series_create' %}">
        {% csrf_token %}
        <div class="grid-wrapper">
            <div class="cell">
                <div class="cell-title"> {{form.title.label}} : </div>
                <div class="cell-input"> {{form.title}} </div>
            </div>
            <div class="cell">
                <div class="cell-title"> {{form.releaseDate.label}} : </div>
                <div class="cell-input"> {{form.releaseDate}} </div>
            </div>
            <div class="cell">
                <div class="cell-title"> {{form.poster.label}} :</div>
                <div class="cell-input"> {{form.poster}} </div>
            </div>
            <div class="grid-wrapper">
                <div class="cell">
                    <div class="cell-title"> {{form.rating.label}} : </div>
                    <div class="cell-input"> {{form.rating}} </div>
                </div>
                <div class="cell">
                    <div class="cell-title"> {{form.status.label}} : </div>
                    <div class="cell-input"> {{form.status}} </div>
                </div>
            </div>
        </div>
        <div class="cell">
            <div class="cell-title"> {{form.description.label}} : </div> 
            <div class="cell-input"> {{form.description}} </div>
        </div>
        <div class="cell"> 
            <div class="cell-title"> {{form.genre.label}} : </div>
            <div class="checkbox-cell"> 
                {% for checkbox in form.genre %}
                    <div> {{ checkbox.tag }} {{ checkbox.choice_label }} </div>
                {% endfor %}    
            </div>
       </div>
       <div class="cell"> 
            <div class="cell-title"> {{form.country.label}} : </div>
                <div class="checkbox-cell"> 
                    {% for checkbox in form.country %}
                        <div> {{ checkbox.tag }} {{ checkbox.choice_label }} </div>
                    {% endfor %}    
                </div>
            </div>
        </div>
        <div class="grid-wrapper-2">
            <div class="cell"> 
                <div class="cell-title"> {{form.cast.label}} : </div>
                <div class="cell-multiinput"> 
                    {{form.cast}} 
                    {{form.cocast1}}
                    {{form.cocast2}}   
                </div>
            </div>
            <div class="cell"> 
                <div class="cell-title"> {{form.director.label}} : </div>
                <div class="cell-multiinput"> 
                    {{form.director}} 
                    {{form.codirector}} 
                </div>
            </div>
            <div class="cell"> 
                <div class="cell-title"> {{form.production.label}} : </div>
                <div class="cell-multiinput"> 
                    {{form.production}} 
                    {{form.coproduction1}}
                    {{form.coproduction2}}   
                </div>
            </div>
        </div>
        <div class="button-wrapper">
            <button id="button" type="submit"> Create Series </button>
        </div>
        <datalist id="production-list">
            {% for production in productions %}
                <option value="{{production}}">
            {% endfor %}
        </datalist>
        <datalist id="director-list">
            {% for director in directors %}
                <option value="{{director}}">
            {% endfor %}
        </datalist>
        <datalist id="cast-list">
            {% for cast in casts %}
                <option value="{{cast}}">
            {% endfor %}
        </datalist>
    </form>
    <!-- Message Box -->
    {% include 'message.html' %}
{% endblock %} 

series_app/templates/series_upload.html
{% extends 'base_page.html' %}

{% load static %}

{% block title %} <title> MovWave | Upload Series </title> {% endblock %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'css/movie_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/series_form.css' %}">
{% endblock %}

{% block content %} 
    <form id="form" class="form upload-form" method="POST" enctype="multipart/form-data" action="{% url 'series_app.series_upload' %}">
        {% csrf_token %}
        <div class="grid-wrapper"> 
            <div class="cell" style="width: auto;">
                <div class="cell-title"> {{form.series.label}} : </div>
                <div class="cell-input"> {{series.title}} ({{series.releaseDate.year}}) </div>
            </div>
            <div class="cell" style="width: auto;">
                <div class="cell-title"> {{form.resolution.label}} : </div>
                <div class="cell-input"> {{form.resolution}} </div>
            </div>
            <div class="cell" style="width: auto;">
                <div class="cell-title"> {{form.season.label}} : </div>
                <div class="cell-input"> {{form.season}} </div>
            </div>
            <div class="cell" style="width: auto;">
                <div class="cell-title"> {{form.episode.label}} : </div>
                <div class="cell-input"> {{form.episode}} </div>
            </div>
        </div>
        <div class="cell" style="width: auto;">
            <div class="cell-title"> {{form.source.label}} : </div>
            <div class="cell-input"> {{form.source}} </div>
        </div>
        <div class="button-wrapper">
            <button id="button" type="submit"> Upload </button>
        </div>
        {{form.sourceFileName}}
        {{form.series}}
    </form>
    <!-- Message Box -->
    {% include 'message.html' %}
    <div class="loading" id="loading">
        <img src="{% static 'images/loading.gif' %}">
        <h1 style="color: whitesmoke;"> Delivering the file . . . . </h1>  
    </div>
{% endblock %} 

{% block script %}
<script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js"
    import { getStorage, ref, getDownloadURL, uploadBytesResumable } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-storage.js";

    const firebaseConfig = {
      apiKey: "AIzaSyCqHB9LNDcFGQ12pW18kYN_bxmjbFpFH-I",
      authDomain: "video-stream-app-6b509.firebaseapp.com",
      projectId: "video-stream-app-6b509",
      storageBucket: "video-stream-app-6b509.appspot.com",
      messagingSenderId: "562471763473",
      appId: "1:562471763473:web:5da474acaf796743163bb0",
      measurementId: "G-CZQJ7EWYQE"
    }

    const app = initializeApp(firebaseConfig)
    const storage = getStorage(app)

    const button = document.querySelector('#button')
    const loading = document.querySelector('#loading')
    const form = document.querySelector('#form')
    
    const season = document.querySelector('#id_season')
    const episode = document.querySelector('#id_episode')
    const source = document.querySelector('#id_source')
    const resolution = document.querySelector('#id_resolution')
    const series = document.querySelector('#id_series')
    const sourceFileName = document.querySelector('#id_sourceFileName')

    document.addEventListener('DOMContentLoaded', () => {
        loading.classList.add('hidden')
    })

    const showLoading = () => {
        loading.classList.remove('hidden')
        form.classList.add('hidden')
        button.classList.add('hidden')
    }

    const hideLoading = () => {
        loading.classList.add('hidden')
        form.classList.remove('hidden')
        button.classList.remove('hidden')
    }

    button.addEventListener('click', async (event) => {
        event.preventDefault()

        const file = source.files[0]
        const filename = file.name
        sourceFileName.value = filename
        
        if(file.type !== 'video/mp4') {
            alert(`Invalid file format ${file.type} !`)
            return
        }

        showLoading()
        
        // Append form values to FormData
        const formData = new FormData(form)
        formData.append('sourceFileName', sourceFileName.value)
        formData.append('resolution', resolution.value)
        formData.append('series', series.value)
        formData.append('season', season.value)
        formData.append('episode', episode.value)

        // Submit the form
        // Save video metadata in database
        const response = await fetch(form.action, {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
            }
        })

        // Saving video metadata successful
        // Upload video to firebase
        if(response.status == '200') {
            console.log(response.status)
            alert('Resource file metadata saved in database successfully.')
            const storageRef = ref(storage, `series/${filename}`);
            const uploadTask = uploadBytesResumable(storageRef, file);

            uploadTask.on('state_changed', 
                (snapshot) => {
                    // Handle progress
                    const progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
                    console.log('Upload is ' + progress + '% done');
                }, 
                (error) => {
                    // Handle error
                    console.error('Upload failed:', error);
                    alert('File upload failed.')
                    hideLoading()
                }, 
                () => {
                    // Handle successful uploads
                    console.log(uploadTask.snapshot.ref.name)
                    hideLoading()
                    alert('Upload uploaded successfully')
                }
            );
        } else {    
            // Saving video metadata fails
            console.log(response.status)
            alert('Error saving resource file metadata in the database.')
            hideLoading()
            return
        }     
    })
  </script>
{% endblock %}