auth_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.auth_login, name='auth_app.auth_login'),
    path('logout/', views.auth_logout, name='auth_app.auth_logout'),
    path('register/', views.auth_register, name='auth_app.auth_register'),
    path('profile/', views.auth_profile, name='auth_app.auth_profile'),
    path('passwordChange/', views.auth_passwordChange, name='auth_app.auth_passwordChange'),
]

movieStreamingApp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('auth/', include('auth_app.urls')),
    path('movie/', include('movie_app.urls')),
    path('series/', include('series_app.urls')),
    path('search/', include('search_app.urls')),
    path('comments/', include('comment_app.urls')),
    path('bookmarks/', include('bookmark_app.urls')),

    path('watchHistory/<str:content_type>', views.watchHistory, name='watchHistory'),

    path('searchTerms/', views.getSearchTerms),

    path('cast/create', views.cast_create, name='cast_create'),
    path('cast/<int:id>', views.cast, name='cast'),
]

movie_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('<int:id>/<str:resolution>', views.movie, name='movie_app.movie'),
    path('<int:id>', views.movie, name='movie_app.movie'),
    path('stream/<str:source>/', views.movie_stream, name='movie_app.movie_stream'),
    path('download/<str:source>/', views.movie_download, name='movie_app.movie_download'),
    path('create/', views.movie_create, name='movie_app.movie_create'),
    path('upload/<int:id>', views.movie_upload, name='movie_app.movie_upload'),
    path('upload/', views.movie_upload, name='movie_app.movie_upload'),
]

movie_app/models.py
from django.db import models
from movieStreamingApp.models import Genre, Country, Production, Director, Cast

class Movie(models.Model):
    title       = models.CharField(max_length=255)
    poster      = models.CharField(max_length=255, unique=True)
    releaseDate = models.DateField()
    description = models.TextField()
    rating      = models.CharField(max_length=5, choices=[('G','G'),('PG','PG'),('PG-13','PG-13'),('R','R'),('NC-17','NC-17')])
    addedDateTime = models.DateTimeField(auto_now_add=True)
    genres      = models.ManyToManyField(Genre, blank=True)
    countries   = models.ManyToManyField(Country, blank=True)
    productions = models.ManyToManyField(Production, blank=True, null=True)
    directors   = models.ManyToManyField(Director, blank=True, null=True)
    casts       = models.ManyToManyField(Cast, blank=True, null=True)
    views       = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class MovieResource(models.Model):
    movie      = models.ForeignKey(Movie, on_delete=models.CASCADE)
    resolution = models.CharField(max_length=5, choices=[('320p','320p'),('480p','480p'),('720p','720p'),('1080p','1080p')])
    source     = models.CharField(max_length=255, unique=True)

    class Meta:
        unique_together = ('movie', 'resolution')

    def __str__(self):
        return self.source

movie_app/forms.py
from django import forms
from datetime import datetime
from .models import Movie, MovieResource
from movieStreamingApp.models import Genre, Country


class MovieForm(forms.ModelForm):
    year_list = range(datetime.now().year, datetime.now().year-200, -1)

    class Meta:
        model = Movie
        fields = ['title','poster','releaseDate','rating','description','genres','countries','productions','directors','casts']

    releaseDate = forms.DateField(
        label='Release Date',
        widget=forms.SelectDateWidget(
            years=year_list
        )
    )

    poster = forms.FileField(
        label='Poster',
        widget=forms.FileInput({
            'accept':'image/jpeg,image/jpg,image/jfif'
        })
    )

    genre = forms.ModelMultipleChoiceField(
        label='Genres',
        queryset = Genre.objects.filter().order_by('name'),
        widget=forms.CheckboxSelectMultiple()
    )

    country = forms.ModelMultipleChoiceField(
        label='Countries',
        queryset = Country.objects.filter().order_by('name'),
        widget=forms.CheckboxSelectMultiple()
    )

    director = forms.CharField(
        label='Directors*',
        required=False,
        widget=forms.TextInput({'list':'director-list'})
    )

    codirector = forms.CharField(
        label='Co-Director - optional',
        required=False,
        widget=forms.TextInput({'list':'director-list'})
    )

    cast = forms.CharField(
        label='Casts*',
        required=False,
        widget=forms.TextInput({'list':'cast-list'})
    )

    cocast1 = forms.CharField(
        label='Co-Cast - optional',
        required=False,
        widget=forms.TextInput({'list':'cast-list'})
    )

    cocast2 = forms.CharField(
        label='Co-Cast - optional',
        required=False,
        widget=forms.TextInput({'list':'cast-list'})
    )

    production = forms.CharField(
        label='Production Companies*',
        required=False,
        widget=forms.TextInput({'list':'production-list'})
    )

    coproduction1 = forms.CharField(
        label='Co-Production Company - optional',
        required=False,
        widget=forms.TextInput({'list':'production-list'})
    )

    coproduction2 = forms.CharField(
        label='Co-Production Company - optional',
        required=False,
        widget=forms.TextInput({'list':'production-list'})
    )

    def clean_title(self):
        value = self.cleaned_data.get('title')
        return value.strip()

    def clean_poster(self):
        value = self.cleaned_data.get('poster')
        if value.content_type not in ['image/jpeg', 'image/jpg', 'image/jfif']:
            raise forms.ValidationError('Poster must be either JPEG or JPG')
        return value

    def clean_director(self):
        director = self.cleaned_data.get('director')
        return director.strip()

    def clean_codirector(self):
        codirector = self.cleaned_data.get('codirector')
        return codirector.strip()
    
    def clean_cast(self):
        cast = self.cleaned_data.get('cast')
        return cast.strip()
    
    def clean_cocast1(self):
        cocast1 = self.cleaned_data.get('cocast1')
        return cocast1.strip()
    
    def clean_cocast2(self):
        cocast2 = self.cleaned_data.get('cocast2')
        return cocast2.strip()

    def clean_production(self):
        production = self.cleaned_data.get('production')
        return production.strip()
    
    def clean_coproduction1(self):
        coproduction1 = self.cleaned_data.get('coproduction1')
        return coproduction1.strip()
    
    def clean_coproduction2(self):
        coproduction2 = self.cleaned_data.get('coproduction2')
        return coproduction2.strip()


#######################################################################


class MovieResourceForm(forms.ModelForm):
    class Meta:
        model = MovieResource
        fields = ['movie', 'resolution','source']

    source = forms.FileField(
        label='Video File',
        widget=forms.FileInput({
            'accept':'video/mp4'
        })
    )

    sourceFileName = forms.CharField(
        widget=forms.TextInput({
            'style':'display:none;',
            'readonly':'readonly'
        })
    )

    def clean_source(self):
        value = self.cleaned_data.get('source')
        if not value.content_type == 'video/mp4':
            raise forms.ValidationError('File must be MP4')
        return value
        

movie_app/views.py
import re
from firebase_admin import storage
from django.contrib import messages
from django.db import IntegrityError
from datetime import datetime, timedelta
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist, EmptyResultSet
from utils.custom_decorators import superuser_required
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.http import StreamingHttpResponse, HttpResponse, HttpResponseRedirect
from utils.file_iterator import file_iterator
from utils.watch_history import add_watchHistory

from . import forms
from comment_app.models import Comment
from .models import MovieResource, Movie
from bookmark_app.models import Bookmark
from comment_app.forms import CommentForm, EditForm
from movieStreamingApp.models import Production, Director, Cast


def movie(request, id, resolution=None):
    """ Send Movie Information """
    if request.method == 'GET':

        try:
            comment_form  = CommentForm()
            edit_form     = EditForm()
            movie         = Movie.objects.get(id=id)
            resolutions   = movie.movieresource_set.values('resolution')
            genres        = movie.genres.filter()
            countries     = movie.countries.filter()
            productions   = movie.productions.filter()
            directors     = movie.directors.filter()
            casts         = movie.casts.filter()

            movie.views = movie.views + 1
            movie.save()

            if request.user.is_authenticated:
                bookmarks = Bookmark.objects.filter(user=request.user, object_id=id, content_type=ContentType.objects.get_for_model(Movie))
                if bookmarks.exists():
                    bookmarked = True
                else:
                    bookmarked = False
            else:
                bookmarked = False

            if resolution == None:
                movie_resource = movie.movieresource_set.first() 
                if(movie_resource is None and request.user.is_superuser):
                    return redirect('movie_app.movie_upload', id=id)
            else:
                movie_resource = movie.movieresource_set.get(resolution=resolution)
            
            context = {
                'movie': movie,
                'movie_resource': movie_resource,
                'resolutions': resolutions,
                'genres': genres,
                'countries': countries,
                'productions': productions,
                'directors': directors,
                'casts': casts,
                'comment_form': comment_form,
                'edit_form': edit_form,
                'bookmarked': bookmarked,
                'content_type':'movies',
            }

            # add to watch history
            if request.user.is_authenticated:
                add_watchHistory(request=request, id=id, content_type=ContentType.objects.get_for_model(Movie))

            return render(request, 'movie.html', context)

        except Exception as e:
            raise e


def movie_stream(request, source):
    # access file from fire storage
    file = storage.bucket().blob(f'movies/{source}')
    file.reload()  
    file_size = file.size

    # get range from user ( initial is 0- )
    range = request.headers.get('Range', None)
    if not range:
        return HttpResponse(status=416)
    
    # split x and y from range: x - y
    byte_range = re.search(r'bytes=(\d+)-(\d*)', range).groups()
    start = int(byte_range[0])

    # 1000Bytes is 0 - 999 just like array, 
    # thus end is either start + chunk or file_size - 1, whichever smaller
    # file_size - 1 to make sure there is no out of bound
    end = min(start + 1000000, file_size - 1)
   
    response = StreamingHttpResponse(file_iterator(file, start, end), status=206)
    response['Content-Range'] = f'bytes {start}-{end}/{file_size}'
    response['Accept-Ranges'] = 'bytes'
    response['Content-Length'] = end - start + 1
    response['Content-Type'] = 'video/mp4'

    return response 


@login_required
def movie_download(request, source):
    expiration = datetime.now() + timedelta(minutes=5)
    download_url = storage.bucket().blob(f'movies/{source}').generate_signed_url(expiration=expiration)
    return render(request, 'movie_download.html', {'download_url':download_url})


@superuser_required
def movie_create(request):
    """ Send the movie create form and Process Data """
    if request.method == 'GET':
        movie_form = forms.MovieForm()
        productions = Production.objects.filter()
        directors = Director.objects.filter()
        casts = Cast.objects.filter()
        context = {
            'form': movie_form,
            'productions': productions,
            'directors': directors,
            'casts': casts,
        }
        return render(request, 'movie_create.html', context)
    
    elif request.method == 'POST':
        movie_form = forms.MovieForm(request.POST,request.FILES)

        if movie_form.is_valid():
            try:
                title        = movie_form.cleaned_data['title']
                releaseDate  = movie_form.cleaned_data['releaseDate']
                description  = movie_form.cleaned_data['description']
                genres       = movie_form.cleaned_data['genre']
                countries    = movie_form.cleaned_data['country']
                poster       = movie_form.cleaned_data['poster']
                rating       = movie_form.cleaned_data['rating']
                production    = movie_form.cleaned_data['production']
                coproduction1 = movie_form.cleaned_data['coproduction1']
                coproduction2 = movie_form.cleaned_data['coproduction2']
                director      = movie_form.cleaned_data['director']
                codirector    = movie_form.cleaned_data['codirector']
                cast          = movie_form.cleaned_data['cast']
                cocast1       = movie_form.cleaned_data['cocast1']
                cocast2       = movie_form.cleaned_data['cocast2']

                bucket = storage.bucket()
                # creates a reference in bucket
                blob = bucket.blob(f'posters/{poster.name}')
                blob.upload_from_file(poster)
                blob.make_public()  
                poster_url = blob.public_url

                new_movie = Movie(title=title, rating=rating, poster=poster_url, releaseDate=releaseDate, description=description)
                new_movie.save()
                new_movie.genres.set(genres)
                new_movie.countries.set(countries)

                # handle productions
                productions = []
                if production != '':
                    production, created = Production.objects.get_or_create(name=production)
                    productions.append(production)
                if coproduction1 != '':
                    coproduction1, created = Production.objects.get_or_create(name=coproduction1)
                    productions.append(coproduction1)
                if coproduction2 != '':
                    coproduction2, created = Production.objects.get_or_create(name=coproduction2)
                    productions.append(coproduction2)
                new_movie.productions.set(productions)

                # handle directors
                directors = []
                if director != '':
                    director, created = Director.objects.get_or_create(name=director)
                    directors.append(director)
                if codirector != '':
                    codirector, created = Director.objects.get_or_create(name=codirector)
                    directors.append(codirector)
                new_movie.directors.set(directors)

                # handle casts
                casts = []
                if cast != '':
                    cast, created = Cast.objects.get_or_create(name=cast)
                    casts.append(cast)
                if cocast1 != '':
                    cocast1, created = Cast.objects.get_or_create(name=cocast1)
                    casts.append(cocast1)
                if cocast2 != '':
                    cocast2, created = Cast.objects.get_or_create(name=cocast2)
                    casts.append(cocast2)
                new_movie.casts.set(casts)

                messages.success(request, 'Movie has been succesfully created')
                return redirect('movie_app.movie_upload', id=new_movie.id)
            
            except Exception as e:
                raise e
            
        return render(request, 'movie_create.html', {'form': movie_form})
            

@superuser_required
def movie_upload(request, id=None):
    """ Before uploading to firebase, save metadata to DB """
    if request.method == 'GET':
        movie = Movie.objects.get(id=id)
        movieResource_form = forms.MovieResourceForm(initial={'movie':movie})
        context = {
            'movie': movie,
            'form': movieResource_form
        }
        return render(request, 'movie_upload.html', context)
    
    elif request.method == 'POST':
        movieResource_form = forms.MovieResourceForm(request.POST, request.FILES) 
        if movieResource_form.is_valid():
            
            try:
                resolution  = movieResource_form.cleaned_data['resolution']
                source      = movieResource_form.cleaned_data['sourceFileName']
                movie       = movieResource_form.cleaned_data['movie']

                new_movieResource = MovieResource(movie=movie,resolution=resolution,source=source)
                new_movieResource.save()
                return HttpResponse(status = 200) 
            
            except IntegrityError as i:
                raise i
                return HttpResponse(status = 500)
            
            except Exception as e:
                raise e

movie_app/templates/movie.html
{% extends 'base_page.html' %}

{% load static %}

{% block title %} <title> MovWave | {{movie.title}} </title> {% endblock %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'css/movie.css' %}">
{% endblock %}

{% block content %} 
    <div class="blackoverlay"></div>
    <div class="video-wrapper">
        <video class="video-player" id="video-player" controls muted="muted">                
            <source src="{% url 'movie_app.movie_stream' source=movie_resource.source %}" type="video/mp4" />
        </video>
    </div>
    <div class="button-wrapper">
        <div>
            <a class="download-button" href="{% url 'movie_app.movie_download' source=movie_resource.source %}"> Download </a>
            {% if user.is_superuser %}
            <a class="upload-button" href="{% url 'movie_app.movie_upload' id=movie.id %}"> Upload </a>
            {% endif %}
        </div>
        <div>
        {% for item in resolutions %}
            {% if item.resolution == movie_resource.resolution%}
                <a class="current-resolution-button" href="{% url 'movie_app.movie' id=movie.id resolution=item.resolution %}"> {{item.resolution}} </a>
            {% else %}
                <a class="available-resolution-button" href="{% url 'movie_app.movie' id=movie.id resolution=item.resolution %}"> {{item.resolution}} </a>
            {% endif %}
        {% endfor %}
        </div>
    </div>
    <div class="metadata-wrapper">
        <div class="poster-wrapper">
            <img src="{{movie.poster}}">
        </div>
        <div class="description-wrapper">
            <div class="header-wrapper">
                <h1> {{movie.title}} ({{movie.releaseDate.year}}) </h1>
                {% if user.is_authenticated %}
                    {% if bookmarked %}
                        <form id="bookmarkForm" method="POST" action="{% url 'bookmark_app.bookmark' content_type='movies' id=movie_resource.movie.id %}">
                            {% csrf_token %}
                            <button title="Remove from Bookmarks" class="bookmark_button" type="submit"> 
                                <svg class="bookmarked" xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 -960 960 960" width="48px" fill="#ffffff"><path d="M200-120v-640q0-33 23.5-56.5T280-840h400q33 0 56.5 23.5T760-760v640L480-240 200-120Zm80-122 200-86 200 86v-518H280v518Zm0-518h400-400Z"/></svg> 
                            </button>
                        </form>
                    {% else %}
                        <form id="bookmarkForm" method="POST" action="{% url 'bookmark_app.bookmark' content_type='movies' id=movie_resource.movie.id %}">
                            {% csrf_token %}
                            <button  title="Add to Bookmarks" class="bookmark_button" type="submit"> 
                                <svg class="not-bookmarked" xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 -960 960 960" width="48px" fill="#ffffff"><path d="M200-120v-640q0-33 23.5-56.5T280-840h400q33 0 56.5 23.5T760-760v640L480-240 200-120Zm80-122 200-86 200 86v-518H280v518Zm0-518h400-400Z"/></svg> 
                            </button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
            <div>
                <p> {{movie.description}} </p>
            </div>
            <div class="grid-wrapper">
                <div> <p> Release Date : </p> </div>
                <div> <p> {{movie.releaseDate}} </p> </div>
                <div> <p> Genre : </p> </div>
                <div> <p> 
                    {% for genre in genres %} 
                        <a href="{% url 'search_app.search' search_type='genre' search=genre.name %}"> {{genre.name}} </a>
                        {% if not forloop.last %} , {% endif %}
                    {% endfor %} 
                </p> </div>
                
                <div> <p> Production : </p> </div>
                {% if productions %}
                    <div> <p> 
                        {% for production in productions %} 
                            <a href="{% url 'search_app.search' search_type='production' search=production.name %}"> {{production.name}} </a>
                            {% if not forloop.last %} , {% endif %}
                        {% endfor %} 
                    </p> </div>
                {% else %}
                    <div> <p> N/A </p> </div>
                {% endif %}
                
                <div> <p> Director : </p> </div>
                {% if directors %}
                    <div> <p> 
                        {% for director in directors %} 
                            <a href="{% url 'search_app.search' search_type='director' search=director.name %}"> {{director.name}} </a>
                            {% if not forloop.last %} , {% endif %}
                        {% endfor %} 
                    </p> </div>                
                {% else %}
                    <div> <p> N/A </p> </div>
                {% endif %}
                
                <div> <p> Cast : </p> </div>
                {% if casts %}
                    <div> <p> 
                        {% for cast in casts %} 
                            <a href="{% url 'search_app.search' search_type='cast' search=cast.name %}"> {{cast.name}} </a>
                            {% if not forloop.last %} , {% endif %}
                        {% endfor %} 
                    </p> </div>                
                {% else %}
                    <div> <p> N/A </p> </div>
                {% endif %}
                
                <div> <p> Country : </p> </div>
                <div> <p> 
                    {% for country in countries %} 
                        <a href="{% url 'search_app.search' search_type='country' search=country.name %}"> {{country.name}} </a>
                        {% if not forloop.last %} , {% endif %}
                    {% endfor %} 
                </p> </div>

                <div> <p> Rating : </p> </div>
                <div> <p> <a href="{% url 'search_app.search' search_type='rating' search=movie.rating %}"> {{movie.rating}} </a> </p> </div>
            </div>
        </div>
    </div>
    <!-- Include Carousel Partial -->
    {% include 'cast_card.html' %}
    <!-- Include Comment Partial -->
    {% include 'comment.html' %}
{% endblock %} 
{% block script %}
    {% if user.is_authenticated %}
    <script src="{% static 'javascript/bookmarkForm_handler.js' %}" defer > </script>
    {% endif %}
{% endblock %}

movie_app/templates/movie_download.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> MovWave | Download </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <p>If the file doesn't start downloading automatically, <a id='download' href="{{download_url}}" download>click here</a>.</p>
    </body>
    <script>
        const download = document.querySelector('#download')
        document.addEventListener('DOMContentLoaded', () => {
            download.click()
        })
    </script>
</html>

movie_app/templates/movie_upload.html
{% extends 'base_page.html' %}

{% load static %}

{% block title %} <title> MovWave | Upload Movie </title> {% endblock %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'css/movie_form.css' %}">
{% endblock %}

{% block content %} 
    <form id="form" class="form upload-form" method="POST" enctype="multipart/form-data" action="{% url 'movie_app.movie_upload' %}">
        {% csrf_token %}
        <div class="grid-wrapper"> 
            <div class="cell" style="width: auto;">
                <div class="cell-title"> {{form.movie.label}} : </div>
                <div class="cell-input"> {{movie.title}} ({{movie.releaseDate.year}}) </div>
            </div>
            <div class="cell" style="width: auto;">
                <div class="cell-title"> {{form.resolution.label}} : </div>
                <div class="cell-input"> {{form.resolution}} </div>
            </div>
        </div>
        <div class="cell" style="width: auto;">
            <div class="cell-title"> {{form.source.label}} : </div>
            <div class="cell-input"> {{form.source}} </div>
        </div>
        <div class="button-wrapper">
            <button id="button" type="submit"> Upload </button>
        </div>
        {{form.sourceFileName}}
        {{form.movie}}
    </form>
    <!-- Message Box -->
    {% include 'message.html' %}
    <div class="loading" id="loading">
        <img src="{% static 'images/loading.gif' %}">
        <h1 style="color: whitesmoke;"> Delivering the file . . . . </h1>  
    </div>
{% endblock %} 

{% block script %}
<script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js"
    import { getStorage, ref, getDownloadURL, uploadBytesResumable } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-storage.js";

    const firebaseConfig = {
      apiKey: "AIzaSyCqHB9LNDcFGQ12pW18kYN_bxmjbFpFH-I",
      authDomain: "video-stream-app-6b509.firebaseapp.com",
      projectId: "video-stream-app-6b509",
      storageBucket: "video-stream-app-6b509.appspot.com",
      messagingSenderId: "562471763473",
      appId: "1:562471763473:web:5da474acaf796743163bb0",
      measurementId: "G-CZQJ7EWYQE"
    }

    const app = initializeApp(firebaseConfig)
    const storage = getStorage(app)

    const button = document.querySelector('#button')
    const loading = document.querySelector('#loading')
    const form = document.querySelector('#form')
    
    const source = document.querySelector('#id_source')
    const resolution = document.querySelector('#id_resolution')
    const movie = document.querySelector('#id_movie')
    const sourceFileName = document.querySelector('#id_sourceFileName')

    document.addEventListener('DOMContentLoaded', () => {
        loading.classList.add('hidden')
    })

    const showLoading = () => {
        loading.classList.remove('hidden')
        form.classList.add('hidden')
        button.classList.add('hidden')
    }

    const hideLoading = () => {
        loading.classList.add('hidden')
        form.classList.remove('hidden')
        button.classList.remove('hidden')
    }

    button.addEventListener('click', async (event) => {
        event.preventDefault()

        const file = source.files[0]
        const filename = file.name
        sourceFileName.value = filename
        
        if(file.type !== 'video/mp4') {
            alert(`Invalid file format ${file.type} !`)
            return
        }

        showLoading()
        
        // Append form values to FormData
        const formData = new FormData(form)
        formData.append('sourceFileName', sourceFileName.value)
        formData.append('resolution', resolution.value)
        formData.append('movie', movie.value)

        // Submit the form
        // Save video metadata in database
        const response = await fetch(form.action, {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
            }
        })

        // Saving video metadata successful
        // Upload video to firebase
        if(response.ok) {
            console.log(response.status)
            alert('Resource file metadata saved in database successfully.')
            const storageRef = ref(storage, `movies/${filename}`);
            const uploadTask = uploadBytesResumable(storageRef, file);

            uploadTask.on('state_changed', 
                (snapshot) => {
                    // Handle progress
                    const progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
                    console.log('Upload is ' + progress + '% done');
                }, 
                (error) => {
                    // Handle error
                    console.error('Upload failed:', error);
                    alert('File upload failed.')
                    hideLoading()
                }, 
                () => {
                    // Handle successful uploads
                    console.log(uploadTask.snapshot.ref.name)
                    hideLoading()
                    alert('Upload uploaded successfully')
                }
            );
        } else {    
            // Saving video metadata fails
            console.log(response.status)
            alert('Error saving resource file metadata in the database.')
            hideLoading()
            return
        }     
    })
  </script>
{% endblock %}